import JSZip from 'jszip'

/**
 * Build a file tree object from flat file array
 */
export const buildFileTree = (files) => {
  const tree = {}
  files.forEach((file) => {
    const parts = file.path.split('/')
    let node = tree
    parts.forEach((part, i) => {
      if (i === parts.length - 1) {
        node[part] = { ...file, isFile: true }
      } else {
        if (!node[part]) node[part] = { isFile: false, children: {} }
        node = node[part].children
      }
    })
  })
  return tree
}

/**
 * Get language from file extension for Monaco Editor
 */
export const getLanguage = (path) => {
  const ext = path.split('.').pop()?.toLowerCase()
  const map = {
    js: 'javascript',
    jsx: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    css: 'css',
    scss: 'scss',
    html: 'html',
    json: 'json',
    md: 'markdown',
    sql: 'sql',
    py: 'python',
    sh: 'shell',
    yml: 'yaml',
    yaml: 'yaml',
    env: 'plaintext',
    txt: 'plaintext',
    gitignore: 'plaintext',
  }
  return map[ext] || 'plaintext'
}

/**
 * Get file icon based on extension
 */
export const getFileIcon = (path) => {
  const ext = path.split('.').pop()?.toLowerCase()
  const name = path.split('/').pop()?.toLowerCase()

  if (name === 'package.json') return '📦'
  if (name === 'readme.md') return '📖'
  if (name === '.env' || name === '.env.example') return '🔒'
  if (name === 'dockerfile') return '🐳'

  const iconMap = {
    jsx: '⚛️',
    tsx: '⚛️',
    js: '🟨',
    ts: '🔷',
    css: '🎨',
    scss: '🎨',
    html: '🌐',
    json: '📋',
    md: '📝',
    sql: '🗄️',
    py: '🐍',
    sh: '⚙️',
    yml: '⚙️',
    yaml: '⚙️',
    png: '🖼️',
    jpg: '🖼️',
    svg: '🖼️',
  }
  return iconMap[ext] || '📄'
}

/**
 * Get color class for framework badge
 */
export const getFrameworkColor = (framework) => {
  const map = {
    React: 'badge-blue',
    'Next.js': 'badge-purple',
    Vue: 'badge-green',
    Angular: 'badge-orange',
    'Node.js': 'badge-green',
    Django: 'badge-green',
    FastAPI: 'badge-purple',
    Laravel: 'badge-orange',
  }
  return map[framework] || 'badge-purple'
}

/**
 * Format relative time
 */
export const timeAgo = (dateStr) => {
  const date = new Date(dateStr)
  const now = new Date()
  const diff = Math.floor((now - date) / 1000)

  if (diff < 60) return 'just now'
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`
  if (diff < 604800) return `${Math.floor(diff / 86400)}d ago`
  return date.toLocaleDateString()
}

/**
 * Generate a ZIP file from project files
 */
export const generateZip = async (project, files) => {
  const zip = new JSZip()
  const folder = zip.folder(project.name || 'project')

  files.forEach((file) => {
    folder.file(file.path, file.content || '')
  })

  // Add README if not present
  if (!files.find((f) => f.path.toLowerCase().includes('readme'))) {
    folder.file(
      'README.md',
      `# ${project.name}\n\n${project.description || ''}\n\nGenerated by [IkoBuild](https://ikobuild.app)\n`
    )
  }

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  return blob
}

/**
 * Download a blob as a file
 */
export const downloadBlob = (blob, filename) => {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Parse AI-generated JSON from a response string (handles code blocks)
 */
export const parseAIJson = (text) => {
  // Try direct parse
  try {
    return JSON.parse(text)
  } catch (_) {}

  // Try extracting from code block
  const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (jsonMatch) {
    try {
      return JSON.parse(jsonMatch[1].trim())
    } catch (_) {}
  }

  // Try finding the first { to last }
  const start = text.indexOf('{')
  const end = text.lastIndexOf('}')
  if (start !== -1 && end !== -1) {
    try {
      return JSON.parse(text.slice(start, end + 1))
    } catch (_) {}
  }

  throw new Error('Failed to parse AI response as JSON')
}

/**
 * Truncate text to n chars with ellipsis
 */
export const truncate = (str, n = 100) =>
  str && str.length > n ? str.slice(0, n) + '…' : str

/**
 * Generate a random slug
 */
export const generateSlug = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') +
  '-' +
  Math.random().toString(36).slice(2, 7)

/**
 * Format bytes to human-readable
 */
export const formatBytes = (bytes) => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`
}

export const cn = (...classes) => classes.filter(Boolean).join(' ')
